version: '3.8'

services:

  user-service:
    build: .
    container_name: user_service
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-db:5432/user-db
    volumes:
      - .:/app
    command: >
      bash -c " rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
